# Setup
title:        Damn Dirty Dev
tagline:      Sometimes I take shortcuts. Sometimes they work out. Sometimes they are very, very dirty.
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Peter Nabicht
  url:        https://nabicht.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
