# Setup
title:        Project or Site name
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Author name
  url:        "https://yoohwankwon.github.io/Learning_in_your_voice" 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
