# Setup
title:        Kartikey Agrawal
tagline:      3D artist, game developer and electronics enthisiast
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Kartikey Agrawal
  url:        http://kartikey0303.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
